apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open_microsoft_2
  annotations:
    github.com/project-slug: Ebeid/open_microsoft_2
spec:
  type: other
  lifecycle: unknown
  owner: guests
